### PR TITLE
add viennacl (minus doc, exmaples dirws)

### PR DESCRIPTION
**Pull request by hughperkins**
address https://github.com/naibaf7/libdnn/issues/5

### CODE REVIEW

**Comment by naibaf7** [comment]
@hughperkins 
Do you think @karlrupp is OK with adding the source as-is?
Wouldn't it be smarter to use a GIT submodule or similar?

**Comment by hughperkins** [comment]
Well, I initially was going to do a git submodule (It's what I'm using for your own code), but there are quite a lot of extra bonus files in the viennacl repo, not necessary for production usage.

**Comment by edgarriba** [comment]
another solution could be with ExternalProject_add/step to install headers and then remove it

**Comment by bhack** [comment]
What is the plan? How we want to support others ops/kernels? If we want to increase ops/kernel coverage actually caffe opencl has almost three implementations with clblas, clblast and Vienna. What we want to do here? /cc @CNugteren

**Comment by hughperkins** [comment]
@bhack well, short-term 'batteries-included' seems not a bad plan.  Longer-term, maybe make the various implementations pluggable, discoverable at runtime?

**Comment by hughperkins** [comment]
oh wait, are you saying, ViennaCl, is optional, eg could choose eg CLblast instead?

**Comment by naibaf7** [comment]
@hughperkins 
No. Caffe can use CLBlast, ViennaCL, clBLAS and ISAAC as BLAS for auxiliary functions and im2col/col2im convolutions.

But libdnn needs ViennaCL at the moment (context handling, kernel launching) but not as BLAS (libdnn does not need a BLAS).

**Comment by hughperkins** [comment]
> But libdnn needs ViennaCL at the moment (context handling, kernel launching)

Ah.  Thats a lot of code for just launching kernels.  But it sounds like you're migrating to some other system soonish?

**Comment by naibaf7** [comment]
@hughperkins 
It is planned to have the possibility of using libdnn only with pure OpenCL/CUDA without ViennaCL; but it's not the top-priority right now.

**Comment by bhack** [comment]
But I don't think that we can increase the kernels/ops coverage without a blas implementaton (if we want to port kernel/ops upstream here  from caffe opencl branch). We want to have the same approach of opencl caffe branch here?

**Comment by hughperkins** [comment]
@bhack Hmmm, that's true.  I've been so focused on convolution, I forgot that basic Linear layers simply, I imagine, call into standard blas3 matrix multiplication.

**Comment by bhack** [comment]
I think that the original @naibaf7 choiche on viennacl was formulated to have device, memory, context etc. This was reivented by many libraries or headers, but he added a dependencies that could give blas ops. But then opencl caffe branch started to support multi blas efforts so device, memory, context and blas are not so correlated anymore. What is the strategy here? Use Vienna only as one of the blas alternative and use something more ligthweigth for bootstrap and management?

@naibaf7 Excuse me if the reconstruction is incorrect or precise.

**Comment by naibaf7** [comment]
@bhack 
This is a very precise description.
Going forward in another direction is just getting a bit delayed due to more people involved with libdnn & Caffe now, such as Intel. So I collect more opinions before doing drastic changes.

**Comment by bhack** [comment]
It is understandable. We need to plan something for GSoC. So while you are trying to collect feedbacks could Edgar propose some API extension mainly to use memory management from Vienna here? 
Next we want to cover ops for a simple Mnist network here and then some more complex net archs.

**Comment by naibaf7** [comment]
@bhack 
Sure, go ahead.

**Comment by bhack** [comment]
Ok. For the general discussion and midterm strategy I think that an extended version of [CLCudaAPI](https://github.com/CNugteren/CLCudaAPI) could be evaluated. Also [libocca](http://libocca.org) has a nice API design for bootstrap and management and has more backends coverage (including HSA).

**Pull request closed without merging**
