### PR TITLE
package export and relocation

### PR DESCRIPTION
**Pull request by edgarriba**

### CODE REVIEW

**Comment by naibaf7** [comment]
@edgarriba 
Thanks for helping me out on the CMake portion :)
I will have time to review/merge and finalize this (acc. your comments) either tomorrow or on Monday :)

**Comment by edgarriba** [comment]
no problem, we need to collaborate. I want to have libdnn working in tiny-cnn ASAP :)

In brief, now we can install + export `GreenteaLibDNN` and import from an external project. (At least tiny-cnn is able to be linked against libdnn).

**Comment by naibaf7** [comment]
@edgarriba 
So the next step is getting the device memory filled and test some convolutions? :)

**Comment by edgarriba** [comment]
right! Between tomorrow/Monday I will do some tests.

**Comment by naibaf7** [comment]
@edgarriba 
Aw too bad my improved kernels are not quite ready yet. The version of libdnn I'm currently working on (0.2.0) will bring the ability to dump the PTX and CUDA / OpenCL code in order to check if it is configured and compiled correctly.

The issue is I have verification problems on libDNN with CUDA 8.0 and the GeForce 1080, so I need to sort that out first before I can bump this repo to 0.2.0.

But you should be able to run some convolutions with 0.1.0 on AMD, Intel and nVidia chips with decent performance.

Intel's spatial convolutions are also promising and should make their way into LibDNN in the midterm, but there the complexity to get it working is just very high at the moment.

**Pull request merged**
